### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by Everrest1** [galiaMuslimova/Slider#15]
Нужно добавить

coverage
disc
.nyc_output

**Comment by galiaMuslimova** [comment]
если я добавлю папку dist в gitignore, то пользователи не смогут устанавливать слайдер?

**Comment by Everrest1** [comment]
> если я добавлю папку dist в gitignore, то пользователи не смогут устанавливать слайдер?

А что в этой папке? Я что-то пока не понимаю
