### ISSUE TITLE
Демо-страница

### ISSUE THREAD

**Issue by Everrest1** [galiaMuslimova/Slider#16]
Демо-страница выполняется отдельной от слайдера структурой и с соблюдением всех требований ко второму заданию. Юнит тесты к демо-странице писать не обязательно

**Comment by galiaMuslimova** [comment]
Выделила демо-страницу в отдельную папку, но не поняла какие именно требования не выполнены.

**Comment by Everrest1** [comment]
> Выделила демо-страницу в отдельную папку, но не поняла какие именно требования не выполнены.

Необходимо также поделить страницу на блоки, и использовать их с помощью pug-миксинов

**Comment by Everrest1** [comment]
Немного странно видеть блок, который называется page

![image](https://user-images.githubusercontent.com/43137324/167196255-53161ef0-3538-4c07-a3a2-a9ac58b0e992.png)

Должна быть возможность передать параметры в слайдер через data-атрибуты

![image](https://user-images.githubusercontent.com/43137324/167196796-5158a91a-d10d-4e0b-818f-7f723233e158.png)

А точно Panel с инпутами должен быть зашит в слайдере?

![image](https://user-images.githubusercontent.com/43137324/167197155-21103b06-521a-473e-9255-001bdc31feeb.png)

**Comment by galiaMuslimova** [comment]
> А точно Panel с инпутами должен быть зашит в слайдере?

Это дает возможность включать/выключать панель. В том числе для пользователя.

**Comment by Everrest1** [comment]
Ничего не изменилось? Примеры слайдеров на демо-странице должны иллюстрировать инициализацию слайдера с разными параметрами, например, указав только два или без параметров. Удобнее это делать с помощью дата-атрибутов у корневого элемента.

![image](https://user-images.githubusercontent.com/43137324/168009338-5b59ac2a-2cce-4581-80b9-7e3144f48116.png)

Я почти уверен, что панелью будут пользоваться единицы из всех пользователей и скорее всего им придётся окольными путями переопределять стили, другой набор инпутов и т.д., а установить этот код придётся всем. Поэтому лучше не добавлять в плагин избыточный функционал

> > А точно Panel с инпутами должен быть зашит в слайдере?
> 
> Это дает возможность включать/выключать панель. В том числе для пользователя.

**Comment by galiaMuslimova** [comment]
> Примеры слайдеров на демо-странице должны иллюстрировать инициализацию слайдера с разными параметрами, например, указав только два или без параметров. Удобнее это делать с помощью дата-атрибутов у корневого элемента.

сделала не через дата-атрибуты, а передачу параметров в виде объекта из json файла, подойдет?

**Comment by Everrest1** [comment]
> 
> сделала не через дата-атрибуты, а передачу параметров в виде объекта из json файла, подойдет?

Не, тут идея именно в том, чтобы можно было инициализировать параметры для конкретного слайдера с помощью data-атрибутов. Это как раз может быть удобно, если их несколько на странице. Помимо этого, значения в этих data-атрибутах должны соответственно обновляться при изменениях значений в слайдере

**Comment by Everrest1** [comment]
Можно лучше использовать spread

![image](https://user-images.githubusercontent.com/43137324/170524417-7d0f2cc7-d197-4d6d-ad75-bcb239ea3335.png)

Значения атрибутов должны обновляться плагином, это часть его функционала

![image](https://user-images.githubusercontent.com/43137324/170527137-efa26e49-d34a-4031-8fc3-428c07f19761.png)

Зачем нужен this.options? Его значения нигде не используются, только записываются

![image](https://user-images.githubusercontent.com/43137324/170527441-2390108f-1752-4047-90eb-32e57ce98ef0.png)

**Comment by Everrest1** [comment]
Если плагин сам принимает параметры через data-атрибуты, то зачем это делать ещё раз?

![image](https://user-images.githubusercontent.com/43137324/170985824-a6bd68db-f6ea-47de-b4a2-23f4c736daa4.png)

**Comment by Everrest1** [comment]
Выражение внутри if ничего не делает

![image](https://user-images.githubusercontent.com/43137324/170990373-ff76aad2-5cc5-4eef-bd62-18170b6d2f4e.png)

Не совсем понимаю зачем хранить параметры в атрибутах инпутов?

![image](https://user-images.githubusercontent.com/43137324/170991514-be2528af-6516-441d-b843-10eb4a3545e9.png)

**Comment by Everrest1** [comment]
А если обновится несколько свойств за раз?
И полагаться на порядок свойств в объекте не лучшая идея, он может быть произвольным

![image](https://user-images.githubusercontent.com/43137324/170993030-989b7340-2882-425c-92a9-998f27cb1003.png)

**Comment by galiaMuslimova** [comment]
> Не совсем понимаю зачем хранить параметры в атрибутах инпутов?

Это установление пороговых значений. Например если меняется max, то для min, to устанавливается его значение как максимально возможное

**Comment by Everrest1** [comment]
> > Не совсем понимаю зачем хранить параметры в атрибутах инпутов?
> 
> Это установление пороговых значений. Например если меняется max, то для min, to устанавливается его значение как максимально возможное

Тогда здесь дублирование, потому что валидация значений производится в слайдере, а инпут подписан на слайдер

**Comment by Everrest1** [comment]
Этот код тогда тоже не нужен

![image](https://user-images.githubusercontent.com/43137324/172109274-1b4b93ae-8fce-4d2f-a644-14355912f004.png)

Есть ошибки ts

![image](https://user-images.githubusercontent.com/43137324/172109303-df66ef70-81d7-4361-a9c9-8019d964bb76.png)
![image](https://user-images.githubusercontent.com/43137324/172109351-6ea1d777-bf07-43ff-a855-d1c0bbacefe2.png)
![image](https://user-images.githubusercontent.com/43137324/172109765-f1d4620f-e880-47d7-b5a5-ba07a10f3cca.png)
