### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by Everrest1** [galiaMuslimova/Slider#17]
При переключении vertical слайдер ломается

![image](https://user-images.githubusercontent.com/43137324/166637824-c4ee1dd8-aa58-47b6-810c-c9b78d92ad6a.png)

**Comment by galiaMuslimova** [comment]
Сорри, я все проверяла, видимо был кэш. Буду внимательнее

**Comment by Everrest1** [comment]
Параметр step работает неверно с дробными числами, например, здесь теряется смысл деления на четверти

![image](https://user-images.githubusercontent.com/43137324/173618552-747c8ca8-9f07-47c7-a38b-61562c056455.png)

В поля невозможно вручную ввести отрицательные значения

![347f794c-0db0-4486-8b04-c5dc5185f668](https://user-images.githubusercontent.com/43137324/173619010-d6b5e758-9a8c-420e-a026-455f4dcc62cc.gif)
