### ISSUE TITLE
jquery best practices

### ISSUE THREAD

**Issue by Everrest1** [galiaMuslimova/Slider#18]
> Плагин должен иметь удобное API для подключения его к элементам на странице и соответствовать best practices по созданию плагинов для jQuery

Можно ориентироваться на [эти](https://www.sitepoint.com/10-tips-better-jquery-plugins/)

Для начала нужно добавить методы инициализации плагина в глобальный объект jQuery

**Comment by galiaMuslimova** [comment]
Прежний способ установить через класс оставила тоже.

**Comment by Everrest1** [comment]
Ещё нужно добавить методы по обновлению и получению параметров слайдера, а так же возможность отслеживать изменения параметров в реальном времени

![image](https://user-images.githubusercontent.com/43137324/168013532-db105142-748b-48ce-a35b-0c67c24aeb2f.png)

**Comment by Everrest1** [comment]
Одним из best practice jQuery плагинов является поддержание цепочки. Т.е. вызов любого метода должен возвращать jQuery объект

$("div#myid").yourPlugin().anotherPlugin().yetAnotherPlugin()

**Comment by Everrest1** [comment]
Так, видимо мы по-разному интерпретировали код из приведённого тобой примера. Текущая реализация не решает задачу сохранения цепочки + дополнительные методы, добавляемые к объекту jQuery могут конфликтовать с другими.

![image](https://user-images.githubusercontent.com/43137324/170528148-a5e3ab47-860e-494f-9ee1-7e21b942e196.png)

В примере же эти проблемы решаются вызовом интересующего метода с помощью указания соответствующей строковой константы. Глобальный объект jQuery же дополняется только одним методом

![image](https://user-images.githubusercontent.com/43137324/170528677-e25bd09f-5b83-41b3-893c-79b5256da209.png)

**Comment by galiaMuslimova** [comment]
Методы getOptions и getValue пока оставила неизменными, т.к. они возвращают значение

**Comment by Everrest1** [comment]
> Методы getOptions и getValue пока оставила неизменными, т.к. они возвращают значение

В этом случае цепочку можно прервать, но оставить только один метод для jQuery, для избежания конфликтов с другими плагинами
