### ISSUE TITLE
Работа с конфигом

### ISSUE THREAD

**Issue by Everrest1** [galiaMuslimova/Slider#20]
Возможно удобнее было бы работать всегда сразу с целым объектом конфига
Тогда эти методы не нужны

![image](https://user-images.githubusercontent.com/43137324/168012476-2510b919-30b7-4059-8c1d-97396144671d.png)

А эти заменить чем-то одним универсальным

![image](https://user-images.githubusercontent.com/43137324/168012627-f52c1617-a79a-4952-80cd-93f153504208.png)

**Comment by galiaMuslimova** [comment]
> А эти заменить чем-то одним универсальным

Оставила две, для параметров слайдера и для панели

**Comment by Everrest1** [comment]
Всё-ещё много лишних методов и не понятно что из этого должно инициализировать вью. На мой взгляд лучше всего с этим справится конструктор что у View, что у Model

![image](https://user-images.githubusercontent.com/43137324/169830629-c8f78a84-e42d-4de0-b4fc-62260a2051d8.png)

Вот этот код с initData выглядит очень странно

![image](https://user-images.githubusercontent.com/43137324/169830802-713a5a4c-2968-40ec-86f2-182c3865e7c0.png)

`setting` это что? Судя по интерфейсу это должен быть список "бегунков" с позицией и значением, но тут почему-то ещё есть значение `moveEnd`. А ещё метод работает только с первым элементом списка, нужен ли в таком случае список?

![image](https://user-images.githubusercontent.com/43137324/169831578-dfb8365f-b03c-4195-974b-36a398cb7918.png)

**Comment by Everrest1** [comment]
Четыре метода, чтобы получить конфиг?
Всё же считаю, что не нужно отделять values от общего конфига, лучше передавать сразу всё, но работать только с необходимыми данными. Так кода получится меньше и он будет чуть более универсальным, особенно это касается внешнего интерфейса, чем он проще, тем лучше

![image](https://user-images.githubusercontent.com/43137324/170994234-b43b8b99-b62e-432d-80a6-3467bd2b6d96.png)

Первая строка не имеет смысла, потому что config переопределяется через следующую

![image](https://user-images.githubusercontent.com/43137324/170993885-a8754734-93b1-402d-9ab0-ecb24db00ba7.png)

Думаю этого типа быть не должно, у нас же есть список конкретных свойств, с которыми работает слайдер и других не предусмотрено

![image](https://user-images.githubusercontent.com/43137324/170993493-c3c52213-2c85-4084-aeac-9b45d312842b.png)

**Comment by Everrest1** [comment]
У тебя два определения defaults, в таких случаях обычно выносят в отдельный файл

![image](https://user-images.githubusercontent.com/43137324/171805407-853b1044-b827-4522-83c2-cf61438eba2c.png)
![image](https://user-images.githubusercontent.com/43137324/171805436-59227a59-20c1-4aa1-b18a-2006733b7bcf.png)

**Comment by Everrest1** [comment]
Есть же observer, работу с dom-элементами нужно оставить во view

![image](https://user-images.githubusercontent.com/43137324/172111613-3fdc1f24-d622-4df2-9cfd-4b47aaaf0eee.png)
