### ISSUE TITLE
View

### ISSUE THREAD

**Issue by Everrest1** [galiaMuslimova/Slider#25]
Немного странно выглядит инициализация, она вроде бы происходит в конструкторе, но не совсем, а вроде бы и в методе init, но не совсем. Нужно что-то более конкретное)

![image](https://user-images.githubusercontent.com/43137324/171809608-c7796ea8-4370-43a9-b18a-d2b6a7b10121.png)

**Comment by Everrest1** [comment]
Всё ещё для инциализации компонента нужно запускать дополнительно методы init, что совсем не удобно

![image](https://user-images.githubusercontent.com/43137324/172112175-f664b84d-4262-40e0-9038-78021ec8599e.png)

**Comment by Everrest1** [comment]
> Все операции с DOM-ом лучше сначала проводить на виртуальных элементах, а потом сразу целиком вставлять в документ страницы.

[п.7.2](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#7.2)

![image](https://user-images.githubusercontent.com/43137324/172798557-6adfb162-bb53-43c6-803e-c52c5eef09a8.png)

**Comment by Everrest1** [comment]
У нас же в рамках слайдера сохранены ссылки на все элементы, я думаю выполнять поиск по dom не совсем неуместно

![image](https://user-images.githubusercontent.com/43137324/172800312-c9968d2d-831c-44a9-a8fe-f15179cc2ddd.png)

**Comment by galiaMuslimova** [comment]
> 

addItem(createItem) остался почти без изменений, т.к. он создает элемент, а встраивание я исправила в другой функции addValues

**Comment by Everrest1** [comment]
Тут осталось

![image](https://user-images.githubusercontent.com/43137324/173615093-6a31252a-cecd-47c7-9015-de93d43ecc15.png)

**Comment by Everrest1** [comment]
Только это позиция не ивента, а курсора

![image](https://user-images.githubusercontent.com/43137324/174100156-04e8a541-1d47-4e1e-84da-62536de0b744.png)
